### ISSUE TITLE
Choix de la stack technique

### ISSUE THREAD

**Issue by florianpanchout** [datagir/simulateurpuissance#4]

**Comment by florianpanchout** [comment]
Je propose une stack React avec Nextjs et Styled Components. Pas besoin, à mon sens, de back ou de librairie style redux.

- **React** : c'est l'outil que l'on utilise tous dans l'équipe
- **Nextjs** : courbe d'apprentissage presque aussi simple que CRA, et beaucoup plus de fonctionnalités intégrées
- **Styled Components** : c'est l'outil que l'on utilise tous dans l'équipe

Pour l'architecture, je propose (sans surprise) de reprendre celle d'Impact CO2 : 

- `pages` avec l'ensemble des pages du site (spécifique à Nextjs). Ici on aura probablement juste un `index.js` au début
- `src` avec tout le reste du code.
- - `components` avec l'ensemble des composants 
- - - `base` avec les composants simple réutilisés partout (un peu comme les atomes pour l'atomic design)
- - - `layout` avec les composants de structure globale (`header`, `footer`, etc.)
- - - `misc` avec les composants qui ne rentrent pas dans les autres dossier
- - - `modals` avec ...les modals
- - - `providers` (qui pourrait être renommé `context`) avec les contexts et leur provider (dans le même fichier, ce sont les seuls composants qui ont deux exports)
- - - `views` avec les composants spécifiques à une page
- - `data` avec l'ensemble des données locales importées au build
- - `hooks` avec ...les hooks
- - `utils` avec quelques fonctions et les bases du css

Les composants (en dehors des `providers` et des `modals`) sont regroupés par feature. Chaque composant enfant est dans un dossier du nom du composant parent, à la racine du composant parent. Si un enfant à plusieurs parents, il migre dans le dossier `misc`. Si un groupe de composants dans le dossier `misc` devient suffisamment important pour mériter son propre dossier, il migre à la racine du dossier `components`, dans un dossier au nom approprié.

Chaque fichier de composant (sauf les providers) n'a qu'un seul export : le composant. 
L'intérieur de ce fichier est structuré comme suit : 

- Import de librairie externes (React, Styled Components, etc.)
- Import de librairie interne (d'autres composants que l'on a créé)
- Déclaration des Styled-Components, par ordre d'apparition dans le composant
- Déclaration du composant

Les fonctions appelées dans le jsx ne sont pas nommées, afin de simplifier la lecture. Si un fichier de composant dépasse les 100 lignes, il doit être divisé en sous-composants.

**Comment by Clemog** [comment]
Top merci ! 
Pourquoi pas besoin de Redux ?

**Comment by florianpanchout** [comment]
Qu'est ce que tu veux faire avec Redux que tu ne peux pas faire plus simplement avec Context ? 

Je trouve Redux beaucoup trop puissant (et donc complexe et verbeux) pour 99% des projets. C'est la librairie de gestion de state historique que tout le monde à (mal) appris, mais ça fait un moment qu'il existe des alternatives plus adaptées à la plupart des usages (Context, react-query, etc.)

**Comment by Clemog** [comment]
Yes j'avais bien en tête le Context, je me demandais justement pourquoi Redux était utilisé parfois à la place de Context
